### ISSUE TITLE
`pybo tok <folder>` not working

### ISSUE THREAD

**Issue by ngawangtrinley** [Esukhia/pybo#11]
`pybo tok <folder>` should be the default behaviour with:

form | lemma | pos.feature | sense

**Comment by o3h** [comment]
creates folder, but no content, no error. tokenizing a string on the command line works, and sorting the contents of a file works.

**Comment by kaldan007** [comment]
pybo version = 0.7.5

To perform above task, you need your file in .txt format inside the input directory. Then you can proceed with this command
`bo tok <folder>`

**Comment by o3h** [comment]
that's exactly what I did; result = empty folder. enclosed screen shot showing text file with text in it, and empty folder(s)
<img width="518" alt="Screen Shot 2021-03-22 at 07 52 53" src="https://user-images.githubusercontent.com/27293846/111946180-aaa3c180-8ae3-11eb-85af-d866dc3bc7ef.png">

**Comment by o3h** [comment]
ok, now I fixed it. thank you.

**Comment by kaldan007** [comment]
ok
