### ISSUE TITLE
suggestion for token conventions

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/pybo#12]
Now we get: 

```
content: "༄༅། "
char types: |punct|punct|punct|space|
type: punct
start in input: 0
length: 4
syl chars in content: None
tag: punct
POS: punct
```
...and only some of the labels correspond to the actual attribute in the token object. For example POS is 'pos' and start in input is start. Maybe better to adapt: 

content
char_types
type
start_in_input
len
syl_chars_in_content
tag
pos

...and have these used for both the token object attribute and the printed out. What do you think?

**Comment by thubtenrigzin** [comment]
fixed in the new release 0.2.1
