### ISSUE TITLE
Command 'pybo' not found

### ISSUE THREAD

**Issue by anbo724** [Esukhia/pybo#12]
I have install the pybo by python3 -m pip install pybo
However, I can not run the follow command:
pybo tok-string "༄༅། །རྒྱ་གར་སྐད་དུ། བོ་དྷི་སཏྭ་ཙརྻ་ཨ་བ་ཏ་ར། བོད་སྐད་དུ། བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ། །
སངས་རྒྱས་དང་བྱང་ཆུབ་སེམས་དཔའ་ཐམས་ཅད་ལ་ཕྱག་འཚལ་ལོ། །བདེ་གཤེགས་ཆོས་ཀྱི་སྐུ་མངའ་སྲས་བཅས་དང༌། །ཕྱག་འོས་ཀུན་ལའང་གུས་པར་ཕྱག་འཚལ་ཏེ། །བདེ་གཤེགས་
སྲས་ཀྱི་སྡོམ་ལ་འཇུག་པ་ནི། །ལུང་བཞིན་མདོར་བསྡུས་ནས་ནི་བརྗོད་པར་བྱ། །"

which ouput "Command 'pybo' not found, did you mean:"

**Comment by o3h** [comment]
for some reason, "bo" and not "pybo" is the command.

**Comment by 10zinten** [comment]
yes, we forgot to update the docs. Thanks for notifying us.
