### ISSUE TITLE
pybo silently processes a file as a folder

### ISSUE THREAD

**Issue by ngawangtrinley** [Esukhia/pybo#13]
![](https://user-images.githubusercontent.com/17675331/111948307-eb1e3200-8b19-11eb-972e-c08cf6f4c0cf.png)

We need either:  
a. an error message asking for a folder  
b. detect it's a file and process as such

This is actually a case of "duck typing" and we probably don't even need to ask users if it's a folder or a file in the first place

**Comment by kaldan007** [comment]
- checks if input dir is directory or not. If input dir is directory, it will iterate over the files inside it and proceed.
- if input dir is a file, it will consider the contain inside it and tokenize
- if input dir is invalid, it will print an error message.
