### ISSUE TITLE
colibri for gramm'n

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/pybo#16]
This seems to go very well actually. Things are working so far as well as it worked with english language. I did not try some of the more advanced features yet, but it should be ok I guess. Let's see. Do you guys use notebooks? If yes, I might create some simple overview with some ready-made convenience functions included.

**Comment by mikkokotila** [comment]
Several observations I have so far: 

- The workflow is cumbersome, which is typical to linguistic tech and can be overcome by creating an intuitive wrapper 
- It seems to be intended for somewhat specific use cases rather than as a generic gram creation solution 
- It is incredibly slow for very basic things like inputting a string and getting in return the grams...1 to 2 orders slower than a simple pure python code to do the same

I think it has some really cool and potentially very useful features that would take time to build well, but for getting ngrams for a whole body of text and then showing some descriptive statistics based on that to help a learner or translator, it will be better to build something from scratch as ngram codes are very simple to write. 

I think the question is with priority; which one is more important, to have n-grams and some statistics capabilities around that, or to have more advanced features like step-grams and unlimited flexibility in terms of assigning the patterns etc.

**Comment by mikkokotila** [comment]
Ok this looks very promising (result of some very basic skipgram codes) with pybo tokenized  ལྷ་བྲག་ཐུགས་སྒྲུབ་དྲག་པོ་རྩལ་གྱི་སྨིན་ལམ་དབང་གི་ཆུ་བོ་ཆེན་མོ་ཁྱེར་བདེར་བསྡེབས་པ་རིན་ཆེན་ཕྲ་མཛེས་ [[1](http://rtz.tsadra.org/index.php/Terdzo-NA-008)]

```
རྡོ་རྗེ་ གཞོན་ནུ་ ནི ༔  -- occurring  2  times
རྡོ་རྗེ་ སེམས་དཔའ་ སོགས ༔  -- occurring  2  times
རྡོ་རྗེ་ བདུད་ འཇོམས་ ༔  -- occurring  2  times
རྡོ་རྗེ་ སྲ་བའི་ གོ ༔  -- occurring  1  times
རྡོ་རྗེ་ དུང་དམར་ འཛིན ༔  -- occurring  2  times
རྡོ་རྗེ་ ཕག་མོ་ མཐིང ༔  -- occurring  4  times
རྡོ་རྗེ་ ཐོད་ཁྲག་ འཛིན ༔  -- occurring  6  times
རྡོ་རྗེ་ དྲིལ་བུ་ འཛིན ༔  -- occurring  2  times
རྡོ་རྗེ་ གཞོན་ནུའི་ སྐུ ༔  -- occurring  3  times
རྡོ་རྗེ་ གནོད་སྦྱིན་ ནི ༔  -- occurring  1  times
རྡོ་རྗེ་ མཆེ་བ་ འཛིན ༔  -- occurring  2  times
རྡོ་རྗེ་ སློབ་དཔོན་ དགོངས ༔  -- occurring  1  times
རྡོ་རྗེ་ མཉམ་ སྦྱོར་བས ༔  -- occurring  2  times
རྡོ་རྗེ་ འཁོར་ལོ་ རིན་པོ་ཆེ ༔  -- occurring  1  times
རྡོ་རྗེ་ སློབ་མ་ སྟེ ༔  -- occurring  1  times
རྡོ་རྗེ་ རྒྱ་གྲམ་ གསལ ༔  -- occurring  1  times
རྡོ་རྗེ་ དྲག་པོ་ རྩལ ༔  -- occurring  2  times
རྡོ་རྗེ་ རྒྱ་གྲམ་ ལྔ ༔  -- occurring  1  times
```
In short summary this is probably the most interesting ngram type result I've seen so far. I tried it with a bunch of words and to my limited understand it worked just as well. The workflow is pretty simple after some wrapping. First you have to identify the available patterns with one command, and then query based on that with  another (if the pattern is not available in the trained model, colibri throws an error). 

[1] http://rtz.tsadra.org/index.php/Terdzo-NA-008

**Comment by drupchen** [comment]
closing as the discussion is inactive
