### ISSUE TITLE
word2vec implementation in Tibetan

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/pybo#17]
Carving out this part from the discussion in #6. 

I've got gensim word2vec built and working to some extent using a small pybo tokenized corpus. There are several things I need to get my head around as I had not used gensim in the past, but things are looking promising and I'm getting similarities out. They might even make some sense (in some cases). I think next I need to try training with a much bigger training dataset, and more epochs, and see what happens. There is a document streaming option for corpus, so I might work towards training with the whole of Rinchen Terdzo as I have it on my local machine. 

Using the model that comes out from gensim, I also tested 'Annoy' nearest neighbor approximation  which seems very promising. There is also LDA available out-of-the-box in gensim, so will look into that as well.

**Comment by ngawangtrinley** [comment]
Wow! that looks really promising. If you're working with larger corpora we really have to improve the segmentation with rules asap.

Anyhow, keep us posted on this one!

**Comment by mikkokotila** [comment]
So ok, I've built a simple pipeline that is executed by:

`model = word2vec_pipeline('rt_train.txt')`

Here a text file is read in, then preprocessed for tokenization, tokenized, preprocessed for vectorization, and finally a gensim word2vec model is trained. Given everything that is being done, the performance is ok: 

```
Building model...
68604 sentences vectorized in 187 seconds.

```
As a sentence parameter I'm using the ། followed by an empty space. 

The above represents roughly 5% of Rinchen Terdzo in terms of titles. So if performance follows linear growth, it takes about an hour to push the entire Rinchen Terdzo through the pipeline. Which is ok, as you would want to do something like that only so many times...Note that I'm working from an older generation laptop and mac os x which is not good with resources for this type of work. My guess is that $50 per month linux with xeon processor will out perform this 1:10.

Then to get the nearest neighbors:

`n = neighbors(model, "སེམས་", indexer='annoy')`

Which yields: 

```
[('སེམས་', 1.0),
 ('མཉམ་པར་', 0.870530977845192),
 ('ལྷན་སྐྱེས་', 0.8077040612697601),
 ('དོན་དམ་', 0.80054572224617),
 ('བདེ་བའི་', 0.7991747111082077),
 ('ཝལ་གྱིས་', 0.7986257076263428),
 ('སྐྱེས་པར་', 0.798562228679657),
 ('དམ་ཡེ་', 0.7891779839992523),
 ('བསྒོམས་', 0.7876778542995453),
 ('རོལ་པར་', 0.7733295112848282)]
```
Very rough, but not terrible. Bear in mind that this is still without any actual model tweaking. I've just formalized the pipeline code and increased the sample size. Next I have to do some study on the way gensim builds the model and its parameter space. I'm still pretty clueless to what's going on under the hood (other than vectors coming out and a neural net being trained). 

In addition to word2vec, there is also the option for FastText, VarEmbed and WordRank. Maybe more...

**Comment by mikkokotila** [comment]
As a small sidenote, I think morphology based approach, such as FastText is going to be far more meaningful for Tibetan than something like word2vec. I think it's fair to say that Tibetan falls under the category of morphologically rich languages.

**Comment by drupchen** [comment]
Great results!
my two cents about the morphology of Tibetan language: there is hardly more morphology that affects the word-endings than the affixed particles.
On the other hand, there is a lot of morphology for constituting lexical units, like starting from  གླང་པོ་(buffalo) and ཆེན་པོ་(big), we end up with གླང་ཆེན་(elephant) or གླང་པོ་ཆེ་(elephant).
But any treatment that comes after the tokenization won't have to deal with this second type of morphology – except if your treatment targets the inner workings of words. 
I hope I am not complicating things...

**Comment by mikkokotila** [comment]
Ok great to hear the results are ok. Gensim is wonderful. It feels very intuitive, fast and flexible. I'm loving very much the fact that there is no need whatsoever for anything language specific. Yet, I think it will be valuable to develop and make available robust word vectors in Tibetan. The Facebook Tibetan vectors are more or less useless due to the fact that it seems to be tokenized by syllable. So I thin the low hanging fruit is to redo the same, but do it with pybo :) I will make the Rinchen Terdzo vectors available as well after some model tweaking. 

I was working on some deep learning related dev over the weekend that arose from the needs related with the title classification problem, I'll start running the codes probably tomorrow, so then I would be able to go back to gensim :)

**Comment by ngawangtrinley** [comment]
Hi @mikkokotila, sorry for not being very responsive lately, I'm in China for a week and am quite busy. There where a couple of interesting hits in the result you just showed, but I think we can do much better than that. One of the main differences between word2vec and sense2vec is that sense2vec can deal with ambiguous terms and much more by including the POS and the syntactic parse trees (if my memory is good for the 2nd) in the vector dimensions. So I'm sure we can do much better if we improve the pos and get the parsing sorted. At the moment the pos are flattened meaning we only have one pos for every token type, making the whole thing useless at the moment. So as far as I'm concerned, I would say that the most urgent is to pair pybo and Spacy and set up a prodigy online page for people to help train both the pos tagger and the parser. I have native staff who can work on this as soon as it's set up. This was actually the main reason we are so keen on working with Spacy. 

I would argue that improving the data is as important as improving the algorithms.

What do you think?

**Comment by mikkokotila** [comment]
@ngawangtrinley I would not look at these results as any kind of benchmark, as they are just blind statistics out of the box. It's just an indication of what might be possible. By the way, this would not work with spaCy out-of-the-box. Also it is slow from the installation onwards, and restrictive in comparison to Gensim. I really want to urge you to consider the following; we're going to remove spaCy entirely from Autonomio at the expense of replacing it with Gensim and Keras embeddings.

It might be that I'm missing something from your use-case, but if you tell me exactly what you expect to get from spaCy, I might be able to comment more clearly. To me it seems that spaCy is more or less 'yesterday' in this field. 

Now what comes to prodigy, it looks potentially interesting. It does look restrictive in the same sense as spaCy i.e. dependent on a pre-created "dictionary" that is specific to the language. Which then becomes a chicken and egg problem. If it's possible to load vectors to it in .vec format which is usually ok, then one could train vecs in Glove or Gensim, and use them in prodigy. Unfortunately you have to pay to play, so can't say for sure. 

When it comes to the POS and so on, I suggest not. You guys have done amazing job, now there is an easy to implement scalable tokenizer for Tibetan!!! :) If you think there are some quick wins in terms of improving the current rules, sure, that makes sense. But for now, I would commit to exploring what is already there, and how to leverage the best. 

I think the important point is that the main use in the modern scene and going forward is not on using POS information anymore, but on word tokenization > vectorization > and then building downstream applications on top of that. Like if a word is a noun or not doesn't matter so much, as long as I get what I'm looking for ; ) Math is beautiful that way.  

Your final point regarding having the staff to go work with annotation, let me find out more about prodigy, and for example if we can use it with any vectors, because then I can just focus on building vectors for you guys, and you can get started :)

**Comment by drupchen** [comment]
closing because discussion is inactive
