### ISSUE TITLE
using unicode data

### ISSUE THREAD

**Issue by eroux** [Esukhia/pybo#24]
Instead of having custom groups in bostrings.py, it would probably be good to use the unicode data. I've gathered the interesting ones in [this file](https://github.com/Esukhia/derge-kangyur/blob/master/scripts/unicodedata-tibetan.csv), which could probably be moved in pybo. Not any kind of emergency though...

**Comment by drupchen** [comment]
solved in 3d330d7

**Comment by eroux** [comment]
thanks!
