### ISSUE TITLE
How to add my own dictionary

### ISSUE THREAD

**Issue by CrystalWLH** [Esukhia/pybo#27]
Hi all,
When I use the 'pybo' tools to segment Tibetan words, there are many of oov words. So I want to know how to add my own dictionary to improve word segmentation accuracy.
Thanks!

**Comment by drupchen** [comment]
Please find an example in this [usecase](https://github.com/Esukhia/pybo/blob/master/usecases/user_entries_in_trie/add_user_entries.py#L15).

Does this answer your need?

**Comment by CrystalWLH** [comment]
I tried this. But there is an error. 
Traceback (most recent call last):
  File "add_user_entries.py", line 15, in <module>
    tok = BoTokenizer('POS', user_word_list=custom_vocab_filenames)
TypeError: __init__() got an unexpected keyword argument 'user_word_list'

**Comment by CrystalWLH** [comment]
I got it. I should modify 'user_word_list' to 'toadd_filenames'. Is it right?

**Comment by drupchen** [comment]
yes, you are right. I forgot to rename the variable in the usecase.

**Comment by drupchen** [comment]
Also, have a look at [this notebook](https://github.com/Esukhia/pybo/blob/master/Using%20BoTokenizer.ipynb) to have a more detailed idea of the inner workings of BoTokenizer. If you want more, read the other two notebooks at the repo's root.

**Comment by CrystalWLH** [comment]
Ok, I know. Thank you very much.

**Comment by drupchen** [comment]
check the latest release that fixes bugs in dynamically deleting entries from the trie (pypi is also updated)
