### ISSUE TITLE
Trie's handing of word list that contains both པར་(photo) and པར་(particle)

### ISSUE THREAD

**Issue by evanyerburgh** [Esukhia/pybo#47]
པར་ meaning photo with a noun POS tag and པར་ with a particle POS tag with an affixed particle hold the same value in the trie. When a word list contains instances of both the noun and the particle, the trie only holds the data of the last one entered.

–Change token objects so that all the data goes into a dict containing everything as value pertaining to the first sense and give it an int (0, 1, ...) as key, stating which is the preferred sense. Sense 0 would be preferable to sense 1, and so on.

–Later, add things like probability calculated from context to decide which sense is correct.

–This would be calculated on the basis of the list of tokens. Each token would have all the possible senses of the entry. In this context, a sense means all the information (affixation, pos, freq, etc. pertaining to an entry).

**Comment by drupchen** [comment]
fixed in 067081b4646af354cbf15b5d45731842dec44d08

Instead of giving a score to each alternative meaning, the attributes `pos`, `lemma` and `freq` are copied from the `meanings` attributes into the Token attributes of the same names. This is how default meaning is chosen.
