### ISSUE TITLE
docstrings

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/pybo#5]
Hey Guys, great to see some action here :) Tried the tokenizer and seems to do a good job :) 

May I suggest that you include doc strings as you go to all functional calls, as it takes much less time when you do it together with publishing the code, rather than afterward. Also makes adoption by others a lot more likely! If you can get something raw in place, I'm happy to improve it from there. That will then act as a basis for a proper user manual. 

Thanks so much!

**Comment by drupchen** [comment]
Putting it raw, I had neither the discipline nor the time to document what I was coding.
I will be adding documentation when I have time.
I saw that you are much better than I am at that and I appreciate you offer to help!

Thank you!
